update to 1.6

diff --git a/checkdeps b/checkdeps
--- a/checkdeps
+++ b/checkdeps
@@ -1,6 +1,6 @@
 #!/usr/bin/perl
 
-# $Header: /home/cvs/thundaural/checkdeps,v 1.9 2004/03/27 18:12:24 jukebox Exp $
+# $Header: /home/cvs/thundaural/checkdeps,v 1.14 2004/06/10 05:57:38 jukebox Exp $
 
 # just a little quick and dirty script to help you make sure you have all the 
 # dependancies installed.  It should really be better than this.  lots of code 
@@ -9,6 +9,7 @@
 # and it should really generate settings/config files for the optional portions
 
 use Data::Dumper;
+use Getopt::Long;
 
 $| = 1;
 
@@ -17,22 +18,19 @@ my $check_server = 0;
 my $softfail = 0;
 
 my $prfailed = 0;
+my $server_found_progs = {};
 
-while(@ARGV) {
-	my $a = shift (@ARGV);
-	if ($a =~ m/^--client/) {
-		$check_client = 1;
-		next;
-	}
-	if ($a =~ m/^--server/) {
-		$check_server = 1;
-		next;
-	}
-	if ($a =~ m/^--softfail/) {
-		$softfail = 1;
-		next;
-	}
-	die("$0: unknown option $a\nUsage: $0 [--client] [--server] [--softfail]\n");
+my %options = (
+	'client!'=>\$check_client,
+	'server!'=>\$check_server,
+	'softfail!'=>\$softfail,
+);
+
+&usage unless GetOptions(%options);
+
+sub usage {
+	print STDERR "Usage: $0 [--client] [--server] [--softfail]\n";
+	exit 1;
 }
 
 if (!$check_client && !$check_server) {
@@ -64,9 +62,10 @@ if ($check_server) {
 	&ok;
 
 	my @modules = qw/DBI DBD::SQLite File::Basename Socket IO::Socket
-	IO::Socket::INET IO::Select IPC::Open2 threads threads::shared
+	IO::Socket::INET IO::Select threads threads::shared
 	Thread::Queue LWP LWP::UserAgent XML::Ximple Data::Dumper
-	CDDB_get
+	CDDB_get Ogg::Vorbis::Decoder Audio::Mad MP3::Info IO::File
+	Audio::DSP Audio::Wav
 	/;
 
 	foreach my $mod (@modules) {
@@ -98,8 +97,6 @@ if ($check_server) {
 		&ok;
 	}
 
-	my $server_found_progs = {};
-
 	my @programs = (
 		{ 'for'=>'ripping audio', 'type'=>'oneof', 'list'=>['dagrab', 'cdda2wav', 'cdparanoia'] },
 		{ 'for'=>'audio info extracting', 'type'=>'must', 'list'=>'cdda2wav' },
@@ -107,12 +104,7 @@ if ($check_server) {
 		{ 'for'=>'cdda2wav version', 'type'=>'grep', 'pattern'=>'^Version 2', 'list'=>'cdda2wav --help 2>&1' },
 		{ 'for'=>'changing the volume', 'label'=>'aumix', 'type'=>'oneof', 'list'=>['aumix-minimal', 'aumix'] },
 		{ 'for'=>'encoding audio', 'type'=>'must', 'list'=>'oggenc' },
-		{ 'for'=>'playing audio', 'type'=>'must', 'list'=>'ogg123' },
-		# no offical support yet
-		#{ 'for'=>'playing audio', 'type'=>'optional', 'list'=>'mpg123' },
-		#{ 'for'=>'playing audio', 'type'=>'optional', 'list'=>'mpg321' },
 		{ 'for'=>'determining device usage', 'type'=>'must', 'list'=>'fuser' },
-		{ 'for'=>'removing files', 'type'=>'must', 'list'=>'rm' },
 		{ 'for'=>'downloading cover art', 'type'=>'must', 'list'=>'php' },
 	);
 
@@ -123,18 +115,25 @@ if ($check_server) {
 		my $label = $prog->{'label'};
 		if ($type eq 'oneof') {
 			my $list = $prog->{'list'};
+			my $found = 0;
 			foreach my $p (@{$list}) {
 				&checking('program', $p);
 				if (my $where = &haveprogram($p)) {
 					&ok($where);
-					$server_found_progs->{$label} = $where
-						if (defined($label) && $label);
-					next NEXTPROG;
+					if (defined($label) && $label) {
+						$server_found_progs->{$label} = $where;
+					} else {
+						$server_found_progs->{$p} = $where;
+					}
+					$found++;
+					#next NEXTPROG;
 				} else {
+					$server_found_progs->{"# $p was not found"} = $p;
 					print " unable to find $p\n";
 				}
 			}
-			&mydie("unable to locate one of ".join(', ', @{$list})." (used for $for) in path\n");
+			&mydie("unable to locate one of ".join(', ', @{$list})." (used for $for) in path\n")
+				if (!$found);
 		} elsif ($type eq 'grep') {
 			&checking('', $prog->{'for'});
 			my $pat = $prog->{'pattern'};
@@ -197,23 +196,26 @@ if ($check_server) {
 		&ok;
 	}
 
-	&runogg123check();
+#	open(T, ">TAProgramLocations.pm") || die("unable to open TAProgramLocations.pm for writing\n");
+#	print T "package TAProgramLocations;\n";
+#	print T "# this file is automaticly generated by checkdeps\n\n";
+#	foreach my $p (keys %{$server_found_progs}) {
+#		my $px = $p;
+#		$px =~ s/\W/_/g;
+#		printf T 'sub %s { \'%s\'; }', $px, $server_found_progs->{$p};
+#		print T "\n";
+#	}
+#	print T "\n1;\n";
+#	print T "\n\n__END__\n\n";
+#	foreach my $p (keys %{$server_found_progs}) {
+#		my $px = $p;
+#		$px =~ s/\W/_/g;
+#		printf T 'PROG_%s=%s', (uc $px), $server_found_progs->{$p};
+#		print T "\n";
+#	}
+#	close(T);
 
-	open(T, ">TAProgramLocations.pm") || die("unable to open TAProgramLocations.pm for writing\n");
-	print T "package TAProgramLocations;\n";
-	print T "# this file is automaticly generated by checkdeps\n\n";
-	foreach my $p (keys %{$server_found_progs}) {
-		my $px = $p;
-		$px =~ s/\W/_/g;
-		printf T 'sub %s { \'%s\'; }', $px, $server_found_progs->{$p};
-		print T "\n";
-	}
-	print T "\n1;\n";
-	close(T);
-
-	print "*********************\n";
-	print "Be sure to move the generated file, TAProgramLocations.pm, into the server directory.\n";
-	print "*********************\n";
+	&write_config_file();
 }
 
 
@@ -250,19 +252,19 @@ if ($check_client) {
 		my $pe = $e; $pe =~ s/^x\d+_//;
 		&checking('headers for library', $pe);
 		if (!$ext{$e}->{'exists'}) {
-			&mydie("Unable to locate $pe libraries.  You can obtain source from ".$ext{$e}->{'srcpage'});
+			&mydie("Unable to locate $pe libraries and header files.  You can obtain source from ".$ext{$e}->{'srcpage'}."  Be sure to install any development related files (like -devel rpms)");
 		}
 		&ok;
 	}
 
 	&checking('perl module', 'SDL');
-	&havemodule('SDL') or &mydie("Unable to locate module SDL.  Grab the necessary version 2.0.2 from the Thundaural website download section.");
+	&havemodule('SDL') or &mydie("Unable to locate module SDL.  Grab the necessary version 2.1.0 from the Thundaural website download section.");
 	&ok;
 
 	&checking('SDL perl version');
 	eval "use SDL;";
-	&mydie("Unable to locate SDL Perl.  Grab the necessary version 2.0.2 from the thundaural website download section.") if ($@ =~ m/^Can't locate/);
-	&mydie("SDL Perl version must be 2.0.2.  Grab it from the thundaural website download section.") unless ($SDL::VERSION =~ /^2\.\d+\.\d+$/);
+	&mydie("Unable to locate SDL Perl.  Grab the necessary version 2.1.0 from the thundaural website download section.") if ($@ =~ m/^Can't locate/);
+	&mydie("SDL Perl version must be 2.1.0.  Grab it from the thundaural website download section.") unless ($SDL::VERSION =~ /^2\.\d+\.\d+$/);
 	&ok($SDL::VERSION);
 
 	&checking('SDL perl supports event push');
@@ -289,76 +291,18 @@ if ($check_client) {
 	}
 }
 
-
-sub runogg123check {
-	# god damn, it is super complex to check for this
-	# if anyone has a better idea, let me know
-
-	my $SCRTMP = "/tmp/testogg123.$$.sh";
-	
-	&checking('ogg123');
-
-	open(X, ">$SCRTMP");
-	print X <<'EOF';
-#!/bin/bash
-
-TMPF=/tmp/testogg123.$$.out
-touch $TMPF
-if [ ! -f $TMPF ]; then
-	exit 8
-fi
-/usr/bin/ogg123 --remote - </dev/null >$TMPF 2>&1 &
-CHP=$!
-/bin/kill -9 $CHP
-RET=0
-grep -F 'unrecognized option' $TMPF >/dev/null 2>/dev/null
-if [ $? == 0 ]; then
-	# ogg123 doesn't support --remote
-	RET=1
-else
-	grep -F '@E Unknown command' $TMPF >/dev/null 2>/dev/null
-	if [ $? == 0 ]; then
-	        # ogg123's remote patch isn't patched to fix stdin close
-	        RET=2
-	fi
-fi
-if [ -f $TMPF ]; then
-	rm -f $TMPF
-fi
-#echo "ret = $RET"
-exit $RET # it is patched!
-
-EOF
-
-	close(X);
-	system("/bin/bash $SCRTMP >/dev/null 2>/dev/null");
-	my $ret = $?;
-	$ret = $ret >> 8;
-	unlink($SCRTMP) if ( -f $SCRTMP);
-
-	my $url = 'http://thwartedefforts.org/jukebox/downloads.php';
-	my $msg;
-	if ($ret == 1) {
-		&mydie("ogg123 doesn't support --remote (see $url)");
-	} elsif ($ret == 2) {
-		&mydie("ogg123's --remote support isn't patched to handle stdin close (see $url)");
-	} elsif ($ret == 0) {
-		&ok("ogg123 is patched for --remote");
-	} else {
-		&mydie("an error occured while checking ogg123");
-	}
-}
-
 ####
 
 sub haveprogram {
 	my $prog = shift;
-	open(X, "which $prog 2>/dev/null |");
-	my $where = <X>;
-	close(X);
-	my $r = $? >> 8;
-	chomp $where;
-	return $r == 1 ? 0 : $where;
+	if (open(X, "which $prog 2>/dev/null |")) {
+		my $where = <X>;
+		chomp $where;
+		close(X);
+		my $r = $? >> 8;
+		return $r == 1 ? 0 : $where;
+	}
+	return 0;
 }
 
 
@@ -385,4 +329,99 @@ sub ok {
 		print " ok\n";
 	}
 }
+
+sub write_config_file {
+
+	my $preamble = <<'EOF';
+# Thundaural Jukebox Configuration File
+#
+# Variable substitution occurs at configuration file read time for $VAR values
+# ${VAR} is not variable substituted during read time, but are run-time substituted
+ 
+# program locations, these should have been generated by the checkdeps script
+EOF
+
+	my $progs = '';
+	
+	foreach my $p (keys %{$server_found_progs}) {
+		if ($p =~ m/^#/) {
+			$progs .= "$p\n";
+		} else {
+			$progs .= sprintf('prog %s:%s%s', $p, $server_found_progs->{$p}, "\n");
+		}
+	}
+
+	my $defaults = <<'EOF';
+ 
+# order is important here -- storagedir and homedir must be defined
+# before dbfile and cmd entries
+ 
+# where the server stores everything, like the audio files and cover art, etc
+storagedir /home/storage
+# the location of the server script, and other support scripts
+homedir .
+ 
+# relative to storagedir if it doesn't begin with a /
+dbfile db/data.db
+ 
+# the address and port that the server should listen on
+#listenhost localhost
+listenport 9000
+ 
+# the number of seconds to pause between songs
+# this only applies to songs that are not in sequence on the same album
+pausebetween 4
+ 
+# list of all the devices, both playback (sound cards) and reading (cdrom drives)
+# device-name:device-info
+# where device-info can be for audio playback devices:
+#     play=/dev/entry:mixer=/dev/entry
+# or for cdrom drives:
+#     read=/dev/entry
+# order of defaults of the same type (play or read) is important -- the first
+# one will determine the 'default' for that type
+# in the case of playback devices, even though we'll send audio output to all
+# the devices, we interact with all of them as a single logical device
+ 
+device main:play=/dev/dsp:mixer=/dev/mixer
+#device backup:play=/dev/dsp1:mixer=/dev/mixer1
+ 
+device cdrom:read=/dev/cdrom
+ 
+# relative to homedir if it doesn't begin with a /
+cmd ripcdrom:ripdisc.pl --dbfile ${DBFILE} --device ${DEVICEFILE} --storagedir ${STORAGEDIR} ${PROGOPTS}
+cmd volumeset:/usr/bin/aumix -d ${DEVICEFILE} -w100 -v${VOLUME}
+cmd volumequery:/usr/bin/aumix -d ${DEVICEFILE} -q
+EOF
+
+	if (open(CONF, ">thundaural-server.conf")) {
+		print CONF $preamble.$progs.$defaults;
+		close(CONF);
+	} else {
+		die("unable to open thundaural-server.conf: $!\n");
+	}
+
+	print "*********************\n";
+	print "You can move the thundaural-server.conf file to /etc/thundaural/server.conf,\n";
+	print "into the server directory, or keep it here -- the server should be able to find it.\n";
+	print "*********************\n";
+
+}
+
+#    Thundaural Jukebox
+#    Copyright (C) 2003-2004  Andrew A. Bakun
+#
+#    This program is free software; you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation; either version 2 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License
+#    along with this program; if not, write to the Free Software
+#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
